##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions
## are met:
##  * Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
##  * Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the distribution.
##  * Neither the name of NVIDIA CORPORATION nor the names of its
##    contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
## EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
## PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
## CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
## EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
## PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
## PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
## OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
## (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
## OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##
## Copyright (c) 2018-2019 NVIDIA Corporation. All rights reserved.
## Copyright (c) 2024 Modified for OpenHarmony (OHOS) platform.

# OHOS platform CMakeLists - based on Linux with OHOS NDK cross-compilation

STRING(TOLOWER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_LOWERCASE)

SET(PHYSX_WARNING_DISABLES "-Wno-invalid-offsetof -Wno-uninitialized -Wno-unused-variable -Wno-variadic-macros -Wno-array-bounds -Wno-strict-aliasing")

# Use Clang with OHOS target flags
SET(PHYSX_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fno-rtti -fno-exceptions -ffunction-sections -fdata-sections -fno-strict-aliasing ${PHYSX_WARNING_DISABLES}" CACHE INTERNAL "PhysX CXX")

# Build debug info for all configurations
SET(PHYSX_CXX_FLAGS_DEBUG   "-O0 -g3" CACHE INTERNAL "PhysX Debug CXX Flags")
SET(PHYSX_CXX_FLAGS_CHECKED "-O3 -g3" CACHE INTERNAL "PhysX Checked CXX Flags")
SET(PHYSX_CXX_FLAGS_PROFILE "-O3 -g" CACHE INTERNAL "PhysX Profile CXX Flags")
SET(PHYSX_CXX_FLAGS_RELEASE "-O3" CACHE INTERNAL "PhysX Release CXX Flags")

# These flags are local to the directory the CMakeLists.txt is in
SET(CMAKE_CXX_FLAGS ${PHYSX_CXX_FLAGS})

SET(CMAKE_CXX_FLAGS_DEBUG   ${PHYSX_CXX_FLAGS_DEBUG})
SET(CMAKE_CXX_FLAGS_CHECKED ${PHYSX_CXX_FLAGS_CHECKED})
SET(CMAKE_CXX_FLAGS_PROFILE ${PHYSX_CXX_FLAGS_PROFILE})
SET(CMAKE_CXX_FLAGS_RELEASE ${PHYSX_CXX_FLAGS_RELEASE})

# Controls PX_NVTX for all projects
SET(NVTX_FLAG "PX_NVTX=0")

# Disable cuda for OHOS
SET(CUDA_FLAG "DISABLE_CUDA_PHYSX")

SET(PHYSX_OHOS_COMPILE_DEFS "${CUDA_FLAG};PX_LINUX=1;PX_OHOS=1;__MUSL__;${PHYSX_AUTOBUILD}" CACHE INTERNAL "Base PhysX preprocessor definitions")

SET(PHYSX_OHOS_DEBUG_COMPILE_DEFS   "NDEBUG;PX_DEBUG=1;PX_CHECKED=1;${NVTX_FLAG};PX_SUPPORT_PVD=1"  CACHE INTERNAL "Debug PhysX preprocessor definitions")
SET(PHYSX_OHOS_CHECKED_COMPILE_DEFS "NDEBUG;PX_CHECKED=1;${NVTX_FLAG};PX_SUPPORT_PVD=1" CACHE INTERNAL "Checked PhysX preprocessor definitions")
SET(PHYSX_OHOS_PROFILE_COMPILE_DEFS "NDEBUG;PX_PROFILE=1;${NVTX_FLAG};PX_SUPPORT_PVD=1"  CACHE INTERNAL "Profile PhysX preprocessor definitions")
SET(PHYSX_OHOS_RELEASE_COMPILE_DEFS "NDEBUG;PX_SUPPORT_PVD=0" CACHE INTERNAL "Release PhysX preprocessor definitions")

# Remove _64 suffix from library names for OHOS
SET(CMAKE_DEBUG_POSTFIX "")
SET(CMAKE_PROFILE_POSTFIX "")
SET(CMAKE_CHECKED_POSTFIX "")
SET(CMAKE_RELEASE_POSTFIX "")

# Include all of the projects
INCLUDE(PhysXFoundation.cmake)
INCLUDE(LowLevel.cmake)
INCLUDE(LowLevelAABB.cmake)
INCLUDE(LowLevelDynamics.cmake)
INCLUDE(PhysX.cmake)
INCLUDE(PhysXCharacterKinematic.cmake)
INCLUDE(PhysXCommon.cmake)
INCLUDE(PhysXCooking.cmake)
INCLUDE(PhysXExtensions.cmake)
INCLUDE(PhysXVehicle.cmake)
INCLUDE(SceneQuery.cmake)
INCLUDE(SimulationController.cmake)
INCLUDE(FastXml.cmake)
INCLUDE(PhysXPvdSDK.cmake)
INCLUDE(PhysXTask.cmake)

# Remove _static suffix from static library names for OHOS
IF(PX_GENERATE_STATIC_LIBRARIES)
	SET_TARGET_PROPERTIES(PhysX PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysX" ARCHIVE_OUTPUT_NAME_CHECKED "PhysX"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysX" ARCHIVE_OUTPUT_NAME_RELEASE "PhysX")
	SET_TARGET_PROPERTIES(PhysXFoundation PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXFoundation" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXFoundation"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXFoundation" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXFoundation")
	SET_TARGET_PROPERTIES(PhysXCommon PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXCommon" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXCommon"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXCommon" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXCommon")
	SET_TARGET_PROPERTIES(PhysXCooking PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXCooking" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXCooking"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXCooking" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXCooking")
	SET_TARGET_PROPERTIES(PhysXExtensions PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXExtensions" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXExtensions"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXExtensions" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXExtensions")
	SET_TARGET_PROPERTIES(PhysXVehicle PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXVehicle" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXVehicle"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXVehicle" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXVehicle")
	SET_TARGET_PROPERTIES(PhysXCharacterKinematic PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXCharacterKinematic" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXCharacterKinematic"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXCharacterKinematic" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXCharacterKinematic")
	SET_TARGET_PROPERTIES(PhysXPvdSDK PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXPvdSDK" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXPvdSDK"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXPvdSDK" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXPvdSDK")
	SET_TARGET_PROPERTIES(LowLevel PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "LowLevel" ARCHIVE_OUTPUT_NAME_CHECKED "LowLevel"
		ARCHIVE_OUTPUT_NAME_PROFILE "LowLevel" ARCHIVE_OUTPUT_NAME_RELEASE "LowLevel")
	SET_TARGET_PROPERTIES(LowLevelAABB PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "LowLevelAABB" ARCHIVE_OUTPUT_NAME_CHECKED "LowLevelAABB"
		ARCHIVE_OUTPUT_NAME_PROFILE "LowLevelAABB" ARCHIVE_OUTPUT_NAME_RELEASE "LowLevelAABB")
	SET_TARGET_PROPERTIES(LowLevelDynamics PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "LowLevelDynamics" ARCHIVE_OUTPUT_NAME_CHECKED "LowLevelDynamics"
		ARCHIVE_OUTPUT_NAME_PROFILE "LowLevelDynamics" ARCHIVE_OUTPUT_NAME_RELEASE "LowLevelDynamics")
	SET_TARGET_PROPERTIES(SceneQuery PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "SceneQuery" ARCHIVE_OUTPUT_NAME_CHECKED "SceneQuery"
		ARCHIVE_OUTPUT_NAME_PROFILE "SceneQuery" ARCHIVE_OUTPUT_NAME_RELEASE "SceneQuery")
	SET_TARGET_PROPERTIES(SimulationController PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "SimulationController" ARCHIVE_OUTPUT_NAME_CHECKED "SimulationController"
		ARCHIVE_OUTPUT_NAME_PROFILE "SimulationController" ARCHIVE_OUTPUT_NAME_RELEASE "SimulationController")
	SET_TARGET_PROPERTIES(FastXml PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "FastXml" ARCHIVE_OUTPUT_NAME_CHECKED "FastXml"
		ARCHIVE_OUTPUT_NAME_PROFILE "FastXml" ARCHIVE_OUTPUT_NAME_RELEASE "FastXml")
	SET_TARGET_PROPERTIES(PhysXTask PROPERTIES
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXTask" ARCHIVE_OUTPUT_NAME_CHECKED "PhysXTask"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXTask" ARCHIVE_OUTPUT_NAME_RELEASE "PhysXTask")
ENDIF()

# Set folder PhysX SDK to all common SDK source projects
SET_PROPERTY(TARGET PhysX PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXCharacterKinematic PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXCommon PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXCooking PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXExtensions PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXVehicle PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET LowLevel PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET LowLevelAABB PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET LowLevelDynamics PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET SceneQuery PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET SimulationController PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET FastXml PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXPvdSDK PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXTask PROPERTY FOLDER "PhysX SDK")
SET_PROPERTY(TARGET PhysXFoundation PROPERTY FOLDER "PhysX SDK")

SET(PHYSXDISTRO_LIBS PhysXFoundation PhysX PhysXCharacterKinematic PhysXPvdSDK PhysXCommon PhysXCooking PhysXExtensions PhysXVehicle)

INSTALL(
    TARGETS ${PHYSXDISTRO_LIBS}
    EXPORT PhysXSDK
    DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile>
    )